# Generated by Django 6.0 on 2026-02-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, help_text="Отметьте для публикации", verbose_name="Опубликовано"),
        ),
    ]
